name: CI pipeline

on:
   push:
    branches: [main]
   pull_request:
    branches: [main]

jobs:
 build:
   runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: say Hello
        run: echo "Hello! CI is working"

      - name: show current directory
        run: pwd

      - name: List files
        run: ls -la
 
 


